name: reHub
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "reHub by opencarecc"
tagline: "an interface of interaction man-machine"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

# Facebook OpenGraph stuff
opengraph:
  title: "reHub by opencarecc"
  url: "http://opencarecc.github.io/rehub/"
  description: "an interface of interaction man-machine"
  image_url: "http://opencarecc.github.io/rehub/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "reHub by opencarecc"
  title: "reHub by opencarecc"
  description: "an interface of interaction man-machine"
  creator: "opencarecc"
  domain: "http://opencarecc.github.io/rehub/"
  image_url: "http://opencarecc.github.io/rehub/assets/OC-Logo-socials.png"
